About p
order-cleaning-services/cleanpro pull request #19
Opened 2023-09-04 15:06 UTC by Natali-Vorobeva

2023-09-05 10:10 UTC, ElPastel requested changes
Небольшие правки

2023-09-05 10:10 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/About/About.jsx
> +					subTitle={'Обосновать удобство предоплаты, цена после&nbsp;уборки не&nbsp;изменится'}
![image](https://github.com/order-cleaning-services/cleanpro/assets/115109501/a7c9f3c8-2f04-4d9a-8621-a0b1dabe8f1b)

нужно убрать фигурные скобки везде, где в пропс передается строка, иначе html entities не конвертируются

2023-09-05 10:10 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Title/Title.jsx
> +		<h2 className="title">{titleText}</h2>
не вижу смысла выделять отдельно компонент Title, я сейчас привожу в порядок глобальные стили и для всех h2 заголовков они будут одинаковые

2023-09-05 10:10 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Сleaners.jsx
> +					</SwiperSlide>
А здесь наоборот лучше выделить отдельный компонент карточки, и рендерить с помощью map, так как в перспективе мы будем получать эти данные с бэка

2023-09-07 09:15 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Title/Title.jsx
> +import '../../../../../../styles/Title.css';
нужно еще везде поменять импорты на 
```suggestion
import './Title.scss';
```

2023-09-07 10:27 UTC, Natali-Vorobeva commented
По слайдеру - Убрала лишние комментарии, оставила только те, что, которые могут понадобиться (чтобы не было ошибок). 
Функция, которая формирует фразу ".... уборок", находится в utils/Quantity.

2023-09-11 07:59 UTC, ElPastel requested changes
Большая просьба, посмотри пожалуйста как сейчас в ветке frontend организована структура файлов, не складывай папки компонентов друг в друга.

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/utils/Quantity.jsx
> +function Quantity(quantityСleaning) {
Это не компонент, расширение нужно изменить на js и предлагаю поменять название на что-то более понятное типа calcCleaningQuantity

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Сleaners.jsx
> +								} */}
Сделай пожалуйста файл с фиктивными данными уборщиков, чтобы мы могли их отрендерить для тестировщиков
![изображение](https://github.com/order-cleaning-services/cleanpro/assets/115109501/1c594d8a-2637-442f-b301-dae432aaf184)

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Slide/Slide.jsx
> +		<SwiperSlide className='slide'>
обертку SwiperSlide нужно вынести в файл Cleaners в map, потому что верстка почему-то ломается если его вставить внутри компонента

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Сleaners.jsx
> +									/>
```suggestion
									return <SwiperSlide><Slide
									key = {slide._id}
									slide={slide}
									/></SwiperSlide>
```

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Cleaners.scss
> +.slide {
перенеси пожалуйста в файл Slide.scss

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Slide/Slide.jsx
> +
```suggestion
const { name, image, mark, quantity } = slide
```

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Slide/Slide.jsx
> +				<p className="slide__title-name">{slide.name}</p>
```suggestion
				<p className="slide__title-name">{name}</p>
```

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Slide/Slide.jsx
> +					<p className="slide__mark">{slide.mark}</p>
```suggestion
					<p className="slide__mark">{mark}</p>
```

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Slide/Slide.jsx
> +			<img className="slide__img" src={slide.image} alt={slide.name} />
```suggestion
			<img className="slide__img" src={slide.image} alt={name} />
```

2023-09-11 07:59 UTC, ElPastel commented on frontend/src/components/pages/AboutPage/Сleaners/Slide/Slide.jsx
> +			<p className="slide__quantity">{slide.quantity}</p>
```suggestion
			<p className="slide__quantity">{calcCleaningQuantity(quantity)}</p>
```

2023-09-13 11:12 UTC, ElPastel approved these changes

2023-09-13 11:12 UTC, merged