added user docs
order-cleaning-services/cleanpro pull request #2
Opened 2023-08-24 12:04 UTC by FedyaevaAS

2023-08-24 14:40 UTC, MrHyde126 requested changes

2023-08-24 14:40 UTC, MrHyde126 commented on docs/openapi-schema.yml
> +  /api/users/generate_password/:
Предлагаю убрать api из эндпоинтов. У нас все равно кроме api и admin ничего нет.

2023-08-24 14:40 UTC, MrHyde126 commented on docs/openapi-schema.yml
> +          maxLength: 250
Нужно ли нам это ограничение? По стандарту 255

2023-08-24 14:40 UTC, MrHyde126 commented on docs/openapi-schema.yml
> +        phone_number:
Предлагаю просто phone

2023-08-24 14:40 UTC, MrHyde126 commented on docs/openapi-schema.yml
> +          pattern: "^[0-9]{10}$"
Я использовал phonenumber_field с регионом RU. Он позволяет указывать номер как с +7, так и с 8. А еще код может быть в скобках, могут быть пробелы и дефисы

2023-08-24 14:40 UTC, MrHyde126 commented on docs/openapi-schema.yml
> +        house_number:
Предлагаю просто house

2023-08-24 14:40 UTC, MrHyde126 commented on docs/openapi-schema.yml
> +          maxLength: 150
По моему это лишнее поле. Номер квартиры в любом случае будет не большим. Точно меньше 150 знаков

2023-08-24 14:40 UTC, MrHyde126 commented on docs/openapi-schema.yml
> +          example: "Qwerty123"
У нас еще спец символ хотя бы один должен быть в пароле

2023-08-25 11:41 UTC, MrHyde126 approved these changes

2023-08-25 14:00 UTC, Reginababaika approved these changes

2023-08-25 14:53 UTC, merged