Работа БД и backend в docker контейнерах.
order-cleaning-services/cleanpro pull request #30
Opened 2023-09-09 12:56 UTC by VictorTsyganov

В данной версии настроена Работа БД и backend в docker контейнерах. Есть пара незначительных изменений в коде для исправления ошибок и корректной настройки работы в контейнерах. Немного изменил значения переменных в .env файле. Просто чтобы удобнее читались. Данные из .env файла сейчас в README это для вновь присоединившихся. Так же настроен доступ к документации (redoc) по ссылке. В README все описано. Как запускать проект с помощью docker compose up.

2023-09-11 16:08 UTC, Star-memory approved these changes

2023-09-11 18:05 UTC, TheSuncatcher222 requested changes
Сделал ревью. Я пока не видел проекта, сложно что-то совсем по делу писать. Но что смог - все тут)

Так как есть пару очень-очень важных моментов - я отправляю ревью с пометкой "доработать"

2023-09-11 18:05 UTC, TheSuncatcher222 commented on README.md
> +http://localhost/
А зачем указывать именной и прямой IP адреса? Просто интересно

2023-09-11 18:05 UTC, TheSuncatcher222 commented on README.md
> +**Содержание файла .env (распологаться он должен в одной папке с файлом manage.py)**
Best practice - это создание .env.example (или .env-example, кто как называет) файла. Есть даже [модули](https://infisical.com/docs/documentation/getting-started/introduction)-генераторы таких файлов

2023-09-11 18:05 UTC, TheSuncatcher222 commented on README.md
> +SECRET_KEY='django-insecure-^9iei$9fqe84qic^#hbp+$ymq+1o+h7a9jckpa&n64t)ekt(nt'
Если так делать - github может начать спамить, что вы запалили свой код)
У меня так было

Ну и SECRET_KEY смысла сообщать нет, так как у нас сайт не на проде и нет централизованной БД

И еще, добавь, пожалуйста, TODO комментарий изменить secret_key на релизе в .env файле. Я моделирую тут ситуацию, что у нас самый настоящий сайт будет. И злоумышленник просто может двигать указатели git, и наткнуться на этот код. Соответственно, нужно его "похоронить" (и код и злоумышленника по возмжоности)

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/Dockerfile
> +COPY requirements.txt .
Можно сразу сделать `COPY . .`

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/cleanpro/settings.py
> +        # 'ENGINE': 'django.db.backends.sqlite3',
Выглядит интересно, но есть вариант покруче, который делает код "как-будто у нас уже прод")
Можно посмотреть [тут ](https://github.com/TheSuncatcher222/foodgram/blob/master/backend/foodgram_backend/settings.py) и [тут](https://github.com/TheSuncatcher222/foodgram/blob/master/backend/foodgram_backend/databases.py) (связанные файлы моего проекта).

Кстати, таким образом можно запускать Pytest на SQLite, если там MySQL или PostrgreSQL стоит!

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/service/migrations/0001_initial.py
> +# Generated by Django 4.2.4 on 2023-09-08 12:14
Миграции лучше не синхронизировать. Вот кто-то сделает feature от ветки, захочет чистую БД - ему Django выкинет ошибку, что миграции есть, а БД нет. И придется удалять ручками все. Не френдли-решение)

Внимание!! Нельзя удалять папку целиком - миграции будут создаваться сломанными, я на этом собаку съел..

Вот такой код подойдет для .gitignore:
`*/migrations/*`
`!*/migrations/__init__.py`

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/service/models.py
>  from django.core.validators import MaxValueValidator, MinValueValidator
Flake8 должен ругнуться, что импорты не в том порядке по идее. Сначала core, потом db.

Не знаю, как у вас принято! Сам каждый push сначала на flake8 всегда проверяю, чтобы чистый код был. Особенно перед push в main или develop. Если тут так не практикуют - такие коменты могу не оставлять)

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/service/models.py
>  class Service_package(models.Model):
А что это такое?..

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/users/models.py
> +        max_length=256, verbose_name='Город',
Ну тоже про код-стайл больше, что везде перенос сразу, а тут 2 параметра в строку

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/users/models.py
> +        blank=False,
[По умолчанию](https://docs.djangoproject.com/en/4.2/ref/models/fields/#null) эти параметры имеют значение `False`, нет необходимости указывать

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/users/models.py
> +        max_length=256, verbose_name='Улица',
Кстати, для особо извращенных (как я) можно еще указывать verbose_name_plural)

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/users/models.py
> +        blank=False,
Аналогично)

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/users/models.py
> +class Adress(models.Model):
Уязвимость для сайта. Можно заспамить 9999....9999 адресов с одними и теме же параметрами. Я пока не знаю, как вы делаете, но примите это во внимание, такую возможность!

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/users/models.py
>  class UserManager(BaseUserManager):
А это зачем, тоже интересно)

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/users/models.py
> +        null=True,
Кстати, про False - сейчас сыграло злую шутку - я увидел, что тут тоже написано blank и null, и автоматом прочитал это как False. А потом увидел `default=None` (то есть в ячейке будет Null) и начал писать про возможность поломки сайта с кодом 500. А потом протер глаза - и убрал коммент)
Это почти как про "мальчика и волков". Но суть в том, что код должен быть удобным для чтения. Так что все же прошу прислушаться к комментарию выше)

2023-09-11 18:05 UTC, TheSuncatcher222 commented on backend/cleanpro/users/models.py
> +    entrance = models.IntegerField(
Я предлагаю тут и еще в некоторых местах подумать над валидацией)
Укажут тут подъезд "-1" - и все))

Либо валидатор, либо [так ](https://docs.djangoproject.com/en/4.2/ref/models/fields/#positivesmallintegerfield) еще можно, но я 100% за валидатор, так как это поле, что я прислал, допускает 0 - что тоже нам не подходит!

2023-09-11 18:05 UTC, TheSuncatcher222 commented on docker-compose.yml
>      image: postgres
Нужна точная версия. если при таком запуске будет скачиваться крайняя (хотя такой синтаксис на моей памяти вообще не заработает, надо писать `postgres latest`) - со временем просто может нарушиться совместимость, и сайт упадет сразу же. Docker на то и Docker, что работать будет всегда. Но надо все жестко фиксировать)

2023-09-11 18:05 UTC, TheSuncatcher222 commented on nginx.conf
> +        root /var/html/;
Странно. Это работает? Просто выше указано, что папка с media у нас `/var/html/**media**/`, а тут даже `alias` не стоит.

2023-09-11 18:05 UTC, TheSuncatcher222 commented on nginx.conf
> +    location /static/admin/ {
Аналогично..

2023-09-12 07:30 UTC, VictorTsyganov commented on README.md
> +http://localhost/
В целом можно указать только один адрес. Указал 2, на случай если кто-то предпочитает использовать именной, а кто-то прямой IP адрес, что бы и тем и тем было удобно.

2023-09-12 07:33 UTC, VictorTsyganov commented on README.md
> +**Содержание файла .env (распологаться он должен в одной папке с файлом manage.py)**
Ок. Можно сделать и так, главное чтобы участники понимали, что ключи реальные, т.к. сейчас это сделано исключительно что бы передать данные остальным участникам проекта. Потом все будет удалено из readme

2023-09-12 07:37 UTC, VictorTsyganov commented on README.md
> +SECRET_KEY='django-insecure-^9iei$9fqe84qic^#hbp+$ymq+1o+h7a9jckpa&n64t)ekt(nt'
Можешь попробовать сам запустить без SECRET_KEY. Локально все запустится, но работать не будет. Я проверял. 
По остальному смотри комментарий выше.

2023-09-12 07:38 UTC, VictorTsyganov commented on backend/cleanpro/Dockerfile
> +COPY requirements.txt .
Можно. Поправлю.

2023-09-12 07:44 UTC, VictorTsyganov commented on backend/cleanpro/cleanpro/settings.py
> +        # 'ENGINE': 'django.db.backends.sqlite3',
Круто. Но большой надобности в этом нет. sqlile один раз подключил, когда миграции не проходили, чтобы постоянно контейнеры не запускать. В остальном и с postgres в контейнерах нормально удается работать.

2023-09-12 07:50 UTC, VictorTsyganov commented on backend/cleanpro/users/models.py
> +        null=True,
Пока не понимаю о чем ты. Лучше напиши как должно быть)

2023-09-12 07:53 UTC, VictorTsyganov commented on backend/cleanpro/users/models.py
> +    entrance = models.IntegerField(
Над валидаторами сейчас кажется работает Владимир Свириденко.

2023-09-12 07:54 UTC, VictorTsyganov commented on docker-compose.yml
>      image: postgres
Ок. Согласен. Исправим.

2023-09-12 07:55 UTC, TheSuncatcher222 commented on README.md
> +http://localhost/
Не вижу смысла, но ладно. Кстати, есть такой момент, что 127.0.0.1 - это зарезервированный адрес для машины, а вот localhost можно перенастраивать (логично - это же именной). Так что надежнее оставить все же именно 127.0.0.1. Кстати, еще можно указать порт. Сейчас у нас в настройках 8000, но от него лучше уйти, так как 8000 - это порт по умолчанию. Представь ситуацию, что у пользователя уже что-то висит в 8000, и он хочет проект открыть. Конечно, эта ответственность и на программисте в т.ч., но для начинающих специалистов такой момент будет не френдли-характера

2023-09-12 07:56 UTC, VictorTsyganov commented on nginx.conf
> +        root /var/html/;
В дипломе работало. Путь для статики тоже прописан по этому принципу и работает. За media не могу сказать с полной уверенностью. Будет понятнее после слияния с фронтом.

2023-09-12 07:56 UTC, TheSuncatcher222 commented on backend/cleanpro/cleanpro/settings.py
> +        # 'ENGINE': 'django.db.backends.sqlite3',
Тогда можно удалить это)

2023-09-12 07:57 UTC, VictorTsyganov commented on nginx.conf
> +    location /static/admin/ {
Работает. Смотри комментарий выше.

2023-09-12 07:58 UTC, TheSuncatcher222 commented on backend/cleanpro/users/models.py
> +        null=True,
Во всех полях всех моделей удалить `null=False` и `blank=False` - вот так)

2023-09-12 08:08 UTC, TheSuncatcher222 approved these changes

2023-09-12 08:25 UTC, merged