Create order with OrderViewSet
order-cleaning-services/cleanpro pull request #67
Opened 2023-09-24 19:24 UTC by VictorTsyganov

Добавлено время в формате integer.
Заказ можно создать двумя способами. 
POST http://localhost/api/order_create/ по старому.  Не стал удалять до изменения во фронте.
POST http://localhost/api/orders/ Для неавторизованного пользователя с указанием данных пользователя. Для авторизованного пользователя без указания данных пользователя.
Не судите строго за оформление По необходимости все подправим. Просто под вечер уже сложно анализировать свой код. Я вообще с трудом понимаю почему он все таки работает))) Вроде не должен работать, но ...

2023-09-26 09:00 UTC, Star-memory approved these changes

2023-09-26 09:57 UTC, TheSuncatcher222 requested changes
Круто сделано!

Есть пара "весомых" моментов, пока напишу "request changes", если что - обсудим

2023-09-26 09:57 UTC, TheSuncatcher222 commented on backend/cleanpro/api/serializers.py
> +from .utils import services_bulk_create, address_create
См. секцию "[Импорты](https://pythonworld.ru/osnovy/pep-8-rukovodstvo-po-napisaniyu-koda-na-python.html#section-8)"

2023-09-26 09:57 UTC, TheSuncatcher222 commented on backend/cleanpro/api/serializers.py
>          for attribute in ('house', 'city', 'street'):
Это зачем тут?

2023-09-26 09:57 UTC, TheSuncatcher222 commented on backend/cleanpro/api/serializers.py
> +        exclude = (
Тут такая же тема, что и с `__all__` - лучше всегда писать include поля

2023-09-26 09:57 UTC, TheSuncatcher222 commented on backend/cleanpro/api/utils.py
> +def services_bulk_create(order, services):
Зачем выносить?

2023-09-26 09:57 UTC, TheSuncatcher222 commented on backend/cleanpro/api/views.py
> +    ServiceSerializer,
Также обращаю внимание на импорты - не в алфавитном порядке

2023-09-26 09:57 UTC, TheSuncatcher222 commented on backend/cleanpro/api/views.py
> +                return CreateUserAndOrderSerializer
Не согласен с практикой. Очень громоздко, никакого KISS. Если пользователь авторизирован - надо запустить процесс создания заказа. Если не авторизирован - сначала запустить процесс создания пользователя, а потом запустить уже готовый процесс для создания

2023-09-26 09:57 UTC, TheSuncatcher222 commented on backend/cleanpro/api/views.py
> +        if not user.is_authenticated:
Очень громоздко. Нужна приватная функция создания пользователя, и сослаться на нее, чем городить монолитный код-полотно. Принцип KISS, опять же.

2023-09-26 09:57 UTC, TheSuncatcher222 commented on backend/cleanpro/price/models.py
> +        # TODO: Нет. Вроде у нас будут услуги, которые будут без картинок.
TODO: сделать
INFO: информация
REPLE: ответный комментарий к TODO или INFO

А то запутаться можно)

2023-09-26 09:57 UTC, TheSuncatcher222 commented on backend/cleanpro/price/models.py
> +        # TODO: Удалить. В разных наборах могут быть одинаковые услуги.
Не удалено

2023-10-03 12:29 UTC, TheSuncatcher222 approved these changes

2023-10-03 15:01 UTC, merged